### ISSUE TITLE
[Bug] 4210 Firmware - 1st Cell shows as 0.00Volts

### ISSUE THREAD

**Issue by ScottishB** [OnewheelCommunityEdition/OWCE_App#55]
**Describe the bug**
When getting the cell voltage - the first cell if the 15 shows 0.00 volts

**To Reproduce**
1. Open the app
2. Click on Battery to expand the option
3. The first cell shows 0.00

**Expected behavior**
Cell voltage of first cell

**Phone (please complete the following information):**
 - Device: [Ipad]
 - OS: 14.4]

**Onewheel (please complete the following information):**
 - Model: Onewheel XR
 - Hardware 4210
 - Firmware: 4150

**Additional context**
Appreciate you mention that 4210 is not supported on the readme but i noticed recent changes suggested it was supported.

**Comment by beeradmoore** [comment]
Hey @TheBR ,
This is a known issue. I assume rode mode also goes to unknown?

If so the issue is the new board unlock method.. OW app unlocks the board for it to be able to send data, switching to OWCE we keep that connection active. If we don't get in to keep the app unlocked, or if the timing is somehow out of sync then the board will lock itself. this then causes all board properties to report 0. In this case the first board cell goes to 0, ride mode goes to 0. 

It may be relevant to add another message saying the board locked itself out from data and to attempt the app swap process again.


A much better solution would be if FM didn't keep the board locked down 🤷‍♂️

**Comment by beeradmoore** [comment]
This should now be resolved (or at least happen a lot less frequently).

The thing we do to keep the board unlocked would only activate every 15sec. This has been changed to run on first connect and then every 15sec. Should avoid a lot more of the issues people were having.
